version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - /tmp/cu_bot/main.db:/app/main.db

  db_backup:
    build:
      context: .
      dockerfile: db_dumb_Dockerfile
    env_file:
      - .env
    volumes:
      - /tmp/cu_bot/main.db:/scripts/main.db
    depends_on:
      - bot